New Templates Added
vedant-jain03/certificate-generator pull request #19
Opened 2022-10-01 13:49 UTC by LostButton

#7 
I have compiled a list of 5 new templates.
Please tell me if I need to change anything within them

![Template9](https://user-images.githubusercontent.com/71197188/193412691-923bdfe1-1f75-490c-82fe-f05c9c036591.gif)
![Template5](https://user-images.githubusercontent.com/71197188/193412693-d501d09b-3be0-4688-bb61-35243748d5e2.png)
![Template6](https://user-images.githubusercontent.com/71197188/193412694-fdb57312-ce1f-46f6-8ace-db6dd6c97c14.png)
![Template7](https://user-images.githubusercontent.com/71197188/193412696-12b6673c-6fe5-4649-a2e1-9c0e22aed220.png)
![Template8](https://user-images.githubusercontent.com/71197188/193412697-0d403cc2-c41d-483b-be89-9e61a57583dc.png)

2022-10-02 04:59 UTC, vedant-jain03 commented
@LostButton This is not the way of adding templates, kindly refer to the current templates implementation. It is way more then just  adding images, let me know if you had doubt!!!

2022-10-02 05:02 UTC, yashikajotwani12 requested changes
[@LostButton](https://github.com/LostButton) This is not the way of adding templates, kindly refer to the current templates implementation. It is way more then just adding images, let me know if you had doubt!!!

2022-10-03 05:06 UTC, yashikajotwani12 requested changes
Hey @LostButton, You need to add your templates here.
I did tried adding and I saw this where the headings were merging, so after adding make sure everything is working.
![Screenshot from 2022-10-03 10-17-32](https://user-images.githubusercontent.com/77020164/193503836-e8442c79-4502-4456-9c9c-368e39b882e1.png)
Add and let me know if you need any help, Good work  :+1:

2022-10-04 03:04 UTC, LostButton commented
The tenplate should be fixed now

2022-10-05 01:04 UTC, LostButton commented
It should be formatted properly now, if not please alert me so i can fix any issues.

2022-10-05 16:47 UTC, yashikajotwani12 commented
Hey @LostButton, you have not added your templates like it is added here https://github.com/vedant-jain03/certificate-generator/blob/8e3021ac5dd66edc84624dfdaca59895efa14a0e/src/components/Homepage.jsx#L156, please add the code in Homepage.jsx.

2022-10-05 16:51 UTC, LostButton commented
> Hey @LostButton, you have not added your templates like it is added here https://github.com/vedant-jain03/certificate-generator/blob/8e3021ac5dd66edc84624dfdaca59895efa14a0e/src/components/Homepage.jsx#L156, please add the code in Homepage.jsx.

But jsx is already updated. It was updated during my second commit?

2022-10-05 16:55 UTC, LostButton commented
OHHHHH I SEE NOW

2022-10-05 17:17 UTC, yashikajotwani12 commented
https://user-images.githubusercontent.com/77020164/194121448-fd00dab4-4a15-4297-bb9e-cfb00027b81a.mp4

The template when clicked just blanks out the screen, please do check this.

2022-10-05 17:58 UTC, LostButton commented
Can you please check whether its only template seven this is happening to?

2022-10-05 18:29 UTC, LostButton commented
Of all things, it was a **single space**.

2022-10-06 00:41 UTC, LostButton commented
@yashikajotwani12 The issue of the blank page should be patched now

2022-10-06 02:59 UTC, yashikajotwani12 commented
Also the size of the templates is bigger, you can add a scrolling part so that the size remains the same.
![Screenshot from 2022-10-06 08-26-07](https://user-images.githubusercontent.com/77020164/194203887-de923471-0d24-4d1c-a59e-5c4d967624e3.png)  
After your changes:
![Screenshot from 2022-10-06 08-28-28](https://user-images.githubusercontent.com/77020164/194204105-8579edcd-7df7-4267-bb9d-795454aae5ff.png)

2022-10-06 05:12 UTC, vedant-jain03 requested changes
You are almost there, here are some changes you need to take care of and then we are finally merging this. Great Work @LostButton 💯 

Also you can make scrolling effect by raising new issues. That don't need to add in this PR contest. WDYT @yashikajotwani12 ?

2022-10-06 05:12 UTC, vedant-jain03 commented on src/components/Homepage.jsx
> +import template9 from "../cert_templates/Template9.png";
```suggestion
import template9 from "../cert_templates/Template9.gif";
```

It should be `.gif`

2022-10-06 05:12 UTC, vedant-jain03 commented on src/components/Homepage.jsx
> +            case " template8":{
```suggestion
            case "template8":{
```
This extra space is making the template 8 broken.

2022-10-06 05:12 UTC, vedant-jain03 commented on src/components/Homepage.jsx
> +                        <div className="author" style={{ position: 'absolute', top: '70%', left: '41%', display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center', textA
```suggestion
                        <div className="author" style={{ position: 'absolute', top: '68%', left: '44%', display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center', textAlign: 'center' }}>
```

This look more centered and clean. WDYT?

2022-10-06 05:12 UTC, vedant-jain03 commented on src/components/Homepage.jsx
> +                            <h1 style={{ fontSize: '20px', color: 'rgb(231, 133, 58)',}}>{this.props.author === '' ? 'Author Name' : this.props.author}</h1>
```suggestion
                            <h1 style={{ fontSize: '20px', color: '#ffff58', fontWeight: '100'}}>{this.props.author === '' ? 'Author Name' : this.props.author}</h1>
```
It looks more decent, WDYT?

2022-10-06 05:12 UTC, vedant-jain03 commented
> Also the size of the templates is bigger, you can add a scrolling part so that the size remains the same. ![Screenshot from 2022-10-06 08-26-07](https://user-images.githubusercontent.com/77020164/194203887-de923471-0d24-4d1c-a59e-5c4d967624e3.png) After your changes: ![Screenshot from 2022-10-06 08-28-28](https://user-images.githubusercontent.com/77020164/194204105-8579edcd-7df7-4267-bb9d-795454aae5ff.png)

Could you please add a new issue for this after we merge this PR, the context of the PR was just to add templates.
WDYT @yashikajotwani12 ?

2022-10-06 05:14 UTC, vedant-jain03 commented on src/components/Homepage.jsx
> +            case " template8":{
This extra space is also in line `176`

2022-10-06 12:11 UTC, LostButton commented
@vedant-jain03 Is this ok?

2022-10-06 13:51 UTC, yashikajotwani12 commented
Hey @LostButton, As suggested by @vedant-jain03  we would open a new issue for the scrolling, but the one thing that I checked is this, do you see the same?

https://user-images.githubusercontent.com/77020164/194330731-05f090eb-5dce-415e-bc0e-46e42d91860c.mp4

Else Everything is fine.

2022-10-06 14:08 UTC, CDPhu commented
@yashikajotwani12 The issue should be fixed. a small redirection error but it should be fixed

2022-10-06 14:12 UTC, yashikajotwani12 commented
Yeah! It is fixed @LostButton, It LGTM.

2022-10-06 14:13 UTC, yashikajotwani12 approved these changes

2022-10-06 14:44 UTC, vedant-jain03 approved these changes
@LostButton Great work, 💯 
Thanks for your valuable contribution!

2022-10-06 14:44 UTC, merged