Add slider
vedant-jain03/certificate-generator pull request #27
Opened 2022-10-13 12:49 UTC by rjrishika

2022-10-14 07:12 UTC, rjrishika commented
@vedant-jain03 please review my pr

2022-10-14 09:38 UTC, vedant-jain03 requested changes
Thanks @rjrishika kindly check my reviews and make the PR update accordingly!

2022-10-14 09:38 UTC, vedant-jain03 commented on src/components/Homepage.jsx
> +                                  <th scope="col"><img src={template7} alt="" /></th>
This is not needed, you can just add this css:
```
.maincontainer .leftmost {
    flex: 0.20 1;
    padding: 1rem;
    display: block;
    align-items: center;
    flex-direction: column;
    color: white;
    border-right: 1px gray solid;
    text-align: center;
    overflow-y: scroll;
}
```

Remove this and please test the code before raising PR!

Thankyou, let me know if you have any doubts

2022-10-14 11:26 UTC, rjrishika commented
changes done

2022-10-15 11:41 UTC, vedant-jain03 requested changes

2022-10-15 11:41 UTC, vedant-jain03 commented on src/components/homepage.css
> +  }
Is this still needed? If not, kindly remove it!

2022-10-15 11:42 UTC, vedant-jain03 commented on src/components/homepage.css
> +  }
Other LGTM, we can merge the PR after this change!

2022-10-17 04:34 UTC, vedant-jain03 approved these changes
@rjrishika Great work, thanks!!!

2022-10-17 04:34 UTC, merged